### ISSUE TITLE
Support for GitSavvy Status and inline diff

### ISSUE THREAD

**Issue by franciscolourenco** [stoivo/sublime-open-in-vscode#1]
I've added the following key bindings to trigger this command in GitSavvy's status view and inline diffs. 
Even though it opens VSCode, it doesn't open the right files. 
Would it be possible to make this package aware of GitSavvy?

```json
     // Open in vscode from GitSavvy inline diff
     {
         "keys": ["o"],
         "command": "vsc_open_in_visal_studio_code",
         "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.inline_diff_view", "operator": "equal", "operand": true }
        ]
     },
     // Open in vscode from GitSavvy status
     {
         "keys": ["o"],
         "command": "vsc_open_in_visal_studio_code",
         "context": [
             { "key": "setting.command_mode", "operator": "equal", "operand": false },
             { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true }
         ]
     }
```
Thanks!

**Comment by stoivo** [comment]
Hello, Thanks for for my first issue :) Good to see that someone is using this package.

Can you test it out? you can clone and and checkout this PR https://github.com/stoivo/sublime-open-in-vscode/pull/2

I have worked on GitSavvy myself so lucky for I I was quite quick for me to add.
